// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCv4p9tXHpAWSbmG6adwqKjffcfLmAHQc',
    appId: '1:563942828556:web:608ee14fc98ff5a3e71c29',
    messagingSenderId: '563942828556',
    projectId: 'flutter-firebase-auth-8cb8d',
    authDomain: 'flutter-firebase-auth-8cb8d.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-8cb8d.appspot.com',
    measurementId: 'G-1PG124L6PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEO56P_TUQOFuzaNEPXj6qQCSXE_4xOp8',
    appId: '1:563942828556:android:5f18d42cf5ea77a7e71c29',
    messagingSenderId: '563942828556',
    projectId: 'flutter-firebase-auth-8cb8d',
    storageBucket: 'flutter-firebase-auth-8cb8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMVNCnIUuhW18VbBhQbmpjANvijpAe6O8',
    appId: '1:563942828556:ios:2917929715d1ac0ae71c29',
    messagingSenderId: '563942828556',
    projectId: 'flutter-firebase-auth-8cb8d',
    storageBucket: 'flutter-firebase-auth-8cb8d.appspot.com',
    iosClientId: '563942828556-68d0i8r48m50qcu25inaldm4ga4aua24.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMVNCnIUuhW18VbBhQbmpjANvijpAe6O8',
    appId: '1:563942828556:ios:2917929715d1ac0ae71c29',
    messagingSenderId: '563942828556',
    projectId: 'flutter-firebase-auth-8cb8d',
    storageBucket: 'flutter-firebase-auth-8cb8d.appspot.com',
    iosClientId: '563942828556-68d0i8r48m50qcu25inaldm4ga4aua24.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );
}
